services:
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: cd LTM_FINALQ && pip install -r requirements.txt
    startCommand: cd LTM_FINALQ && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET_KEY
        generateValue: true
